// <auto-generated />
using System;
using BoekhoudAssistent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoekhoudAssistent.Migrations
{
    [DbContext(typeof(BoekhoudAssistentContext))]
    [Migration("20240918170823_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoekhoudAssistent.Models.BKFP", b =>
                {
                    b.Property<int>("BUKRS")
                        .HasColumnType("int");

                    b.Property<int>("BELNR")
                        .HasColumnType("int");

                    b.Property<int>("GJAHR")
                        .HasColumnType("int");

                    b.Property<string>("BLART")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BLDAT")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BUDAT")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CPUDT")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("CPUTM")
                        .HasColumnType("time");

                    b.Property<string>("MONAT")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("BUKRS", "BELNR", "GJAHR");

                    b.ToTable("BKFP");
                });

            modelBuilder.Entity("BoekhoudAssistent.Models.BSEG", b =>
                {
                    b.Property<int>("BUKRS")
                        .HasColumnType("int");

                    b.Property<int>("BELNR")
                        .HasColumnType("int");

                    b.Property<int>("GJAHR")
                        .HasColumnType("int");

                    b.Property<int>("BUZEI")
                        .HasColumnType("int");

                    b.Property<string>("AUGBL")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("AUGCP")
                        .HasColumnType("date");

                    b.Property<DateOnly>("AUGDT")
                        .HasColumnType("date");

                    b.Property<string>("BSCHL")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BUZID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("BUKRS", "BELNR", "GJAHR", "BUZEI");

                    b.ToTable("BSEG");
                });
#pragma warning restore 612, 618
        }
    }
}
